// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhdkcplqibusvypvxcsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZGtjcGxxaWJ1c3Z5cHZ4Y3NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzM3NzMsImV4cCI6MjA1NzcwOTc3M30.dZt-TVNX9WkigGGq8xbeAO4dVFmbvQ5Z6ru_GAFG7XE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);